### ISSUE TITLE
Parse error or missing code with single-line comments.

### ISSUE THREAD

**Issue by dsthilaire** [lukekarrys/moonboots-static#8]
The attached image is some code I have in one of my ampersand views.
![moonboots bug rpt](https://cloud.githubusercontent.com/assets/12299562/9420514/3dbffb94-481b-11e5-80b0-52d9c38bfa9a.png)

When I try to build this, there is actually an error that gets thrown (also in an attached image) 
![moonboots bug rpt 2](https://cloud.githubusercontent.com/assets/12299562/9420517/45d8fd44-481b-11e5-968f-b7e5e5122e79.png)

.  I’ve tracked the problem down to using a single-line comment within the bindings with a square-bracketed multi-binding after it (see the area with the orange background).  I was able to fix this by changing the single-line comment (//) to a multi-line comment (/* */).  I didn’t bother converting all the other single-line comments to multi-line comments, though, and today I found another issue with single-line comments – they can cause entire chunks of code to be omitted from the minified Javascript.  The entire block with the green background is missing from the file generated by Moonboots.  I was able to fix the problem again by converting the single-line comments to multi-line.

**Comment by lukekarrys** [comment]
Thanks for the issue @dsthilaire. Do you think you could create a minimal test case reproducing the bug(s) (perhaps in a gist)? That would help immensely towards figuring out where the root of the issue is and how we could go about fixing it.
